server:
	port: 8081

spring:
    main:
        allow-bean-definition-overriding: true
    application:
      name: negocio-cobranza-rest
    datasource:
    	url:jdbc:h2:mem:TEST;MVCC=true;DB_CLOSE_DELAY=-1;MODE=Oracle
    	username:sa
    	password:
    	driver-class-name:org.h2.Driver
    	platform:h2
jpa:
	hibernate:
		ddl-auto:none
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

